# Generated by Django 5.2.7 on 2025-11-04 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_unlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
